/*
 * This file is generated by jOOQ.
*/
package com.fantj.daos;


import com.generator.tables.User;
import com.generator.tables.records.UserRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.stereotype.Component;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.fantj.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER_, com.fantj.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER_, com.fantj.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.fantj.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fantj.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fantj.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER_.ID, value);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.fantj.pojos.User> fetchByAddress(String... values) {
        return fetch(User.USER_.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<com.fantj.pojos.User> fetchByBirthday(LocalDateTime... values) {
        return fetch(User.USER_.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.fantj.pojos.User> fetchBySex(String... values) {
        return fetch(User.USER_.SEX, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.fantj.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER_.USERNAME, values);
    }
}
