/*
 * This file is generated by jOOQ.
*/
package com.fantj.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1416697343;

    private Integer       id;
    private String        address;
    private LocalDateTime birthday;
    private String        sex;
    private String        username;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.address = value.address;
        this.birthday = value.birthday;
        this.sex = value.sex;
        this.username = value.username;
    }

    public User(
        Integer       id,
        String        address,
        LocalDateTime birthday,
        String        sex,
        String        username
    ) {
        this.id = id;
        this.address = address;
        this.birthday = birthday;
        this.sex = sex;
        this.username = username;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public LocalDateTime getBirthday() {
        return this.birthday;
    }

    public void setBirthday(LocalDateTime birthday) {
        this.birthday = birthday;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(birthday);
        sb.append(", ").append(sex);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
