/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.routines.Findbyid;

import javax.annotation.Generated;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in user
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>user.findById</code>
     */
    public static void findbyid(Configuration configuration, Integer pid) {
        Findbyid p = new Findbyid();
        p.setPid(pid);

        p.execute(configuration);
    }
}
